#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define MAX_PARTICIPANTES 30
#define MIN_NUMERO 1
#define MAX_NUMERO 75
#define MAX_BOLAS 75
#define MAX_TARJETAS_JUGADOR 2
#define MAX_JUGADORES_JUEZ 5
#define MAX_FILA 5
#define MAX_COLUMNA 5
#define TIEMPO_INICIO 1

//SIGUSR1	 30,10,16
//SIGUSR2	 31,12,17
#define SIGBINGO 10
#define SIGGANADOR 12
#define SIGIMPOSTOR 16
#define SIGVERIFICAR 17
#define SIGFELICITACIONES 30
#define SIGFINALIZAR 31

#define TAM_PANTALLA_X 1000
#define TAM_PANTALLA_Y 485
#define MANUAL 0
#define AUTOMATICO 1


#endif // DEFINES_H_INCLUDED
